### ISSUE TITLE
Assume objects in entities are entity

### ISSUE THREAD

**Issue by gwire** [rdap-org/client.rdap.org#2]
It appears that cscglobal.com produces json where some of the objects in `entity` do not have an `objectClassName: entity`. The client does not parse these.

example:
https://client.rdap.org/?type=url&object=https%3A//apis.cscglobal.com/dbs/rdap-api/v1/domain/ITV.COM

I understand that this label is a REQUIRE in RFC 9083, but from a user (rather than an implementer) perspective it would be good to see the value parsed.

**Comment by gbxyz** [comment]
A basic conformance error on the server side shouldn't require workarounds on the client side. Have you reported this issue to CSC or to ICANN compliance?

**Comment by gbxyz** [comment]
I've updated the validator to correctly report an error for missing `objectClassName` properties.

To report an issue with an RDAP server to ICANN, go to https://icann-nsp.my.site.com/compliance/s/registration-data.
